import {
  AiOutlineArrowLeft,
  AiOutlineArrowRight,
  AiOutlineReload,
  AiOutlineMenu,
  AiOutlineCheck,
  AiOutlineCheckCircle,
  AiOutlineDown,
  AiOutlineLeft,
  AiOutlineRight,
  AiOutlineUp,
  AiOutlineColumnHeight,
  AiOutlineClockCircle,
  AiOutlineHeart,
  AiOutlineHome,
  AiOutlineSearch,
  AiOutlineMinus,
  AiOutlinePlus,
  AiOutlinePhone,
  AiOutlineShoppingCart,
  AiOutlineUser,
  AiOutlineCloseCircle,
  AiOutlineClose,
} from "react-icons/ai";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: AiOutlineArrowLeft,
  ArrowRight: AiOutlineArrowRight,
  ArrowPath: AiOutlineReload,
  Menu: AiOutlineMenu,
  Check: AiOutlineCheck,
  CheckCircle: AiOutlineCheckCircle,
  ChevronDown: AiOutlineDown,
  ChevronLeft: AiOutlineLeft,
  ChevronRight: AiOutlineRight,
  ChevronUp: AiOutlineUp,
  ChevronsUpDown: AiOutlineColumnHeight,
  Clock: AiOutlineClockCircle,
  Heart: AiOutlineHeart,
  Home: AiOutlineHome,
  Search: AiOutlineSearch,
  Minus: AiOutlineMinus,
  Plus: AiOutlinePlus,
  Cart: AiOutlineShoppingCart,
  User: AiOutlineUser,
  Phone: AiOutlinePhone,
  XCircle: AiOutlineCloseCircle,
  X: AiOutlineClose,
};
