import {
  BiArrowBack,
  BiRightArrowAlt,
  BiRefresh,
  BiMenu,
  BiCheck,
  BiCheckCircle,
  BiChevronDown,
  BiChevronLeft,
  BiChevronRight,
  BiChevronUp,
  BiExpandVertical,
  BiTime,
  BiHeart,
  BiHome,
  BiSearch,
  BiMinus,
  BiPlus,
  BiPhone,
  BiShoppingBag,
  BiUser,
  BiXCircle,
  BiX,
} from "react-icons/bi";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: BiArrowBack,
  ArrowRight: BiRightArrowAlt,
  ArrowPath: BiRefresh,
  Menu: BiMenu,
  Check: BiCheck,
  CheckCircle: BiCheckCircle,
  ChevronDown: BiChevronDown,
  ChevronLeft: BiChevronLeft,
  ChevronRight: BiChevronRight,
  ChevronUp: BiChevronUp,
  ChevronsUpDown: BiExpandVertical,
  Clock: BiTime,
  Heart: BiHeart,
  Home: BiHome,
  Search: BiSearch,
  Minus: BiMinus,
  Plus: BiPlus,
  Cart: BiShoppingBag,
  User: BiUser,
  Phone: BiPhone,
  XCircle: BiXCircle,
  X: BiX,
};
