import {
  BsArrowLeft,
  BsArrowRight,
  BsArrowRepeat,
  BsList,
  BsCheck,
  BsCheckCircle,
  BsChevronDown,
  BsChevronLeft,
  BsChevronRight,
  BsChevronUp,
  BsChevronExpand,
  BsClock,
  BsHeart,
  BsHouse,
  BsSearch,
  BsDash,
  BsPlus,
  BsTelephone,
  BsCart3,
  BsPerson,
  BsXCircle,
  BsX,
} from "react-icons/bs";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: BsArrowLeft,
  ArrowRight: BsArrowRight,
  ArrowPath: BsArrowRepeat,
  Menu: BsList,
  Check: BsCheck,
  CheckCircle: BsCheckCircle,
  ChevronDown: BsChevronDown,
  ChevronLeft: BsChevronLeft,
  ChevronRight: BsChevronRight,
  ChevronUp: BsChevronUp,
  ChevronsUpDown: BsChevronExpand,
  Clock: BsClock,
  Heart: BsHeart,
  Home: BsHouse,
  Search: BsSearch,
  Minus: BsDash,
  Plus: BsPlus,
  Cart: BsCart3,
  User: BsPerson,
  Phone: BsTelephone,
  XCircle: BsXCircle,
  X: BsX,
};
