import {
  CgArrowLeft,
  CgArrowRight,
  CgRedo,
  CgMenu,
  CgCheck,
  CgCheckO,
  CgChevronDown,
  CgChevronLeft,
  CgChevronRight,
  CgChevronUp,
  CgSelectO,
  CgTimer,
  CgHeart,
  CgHome,
  CgSearch,
  CgMathMinus,
  CgMathPlus,
  CgPhone,
  CgShoppingBag,
  CgUser,
  CgCloseO,
  CgClose,
} from "react-icons/cg";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: CgArrowLeft,
  ArrowRight: CgArrowRight,
  ArrowPath: CgRedo,
  Menu: CgMenu,
  Check: CgCheck,
  CheckCircle: CgCheckO,
  ChevronDown: CgChevronDown,
  ChevronLeft: CgChevronLeft,
  ChevronRight: CgChevronRight,
  ChevronUp: CgChevronUp,
  ChevronsUpDown: CgSelectO,
  Clock: CgTimer,
  Heart: CgHeart,
  Home: CgHome,
  Search: CgSearch,
  Minus: CgMathMinus,
  Plus: CgMathPlus,
  Cart: CgShoppingBag,
  User: CgUser,
  Phone: CgPhone,
  XCircle: CgCloseO,
  X: CgClose,
};
