import {
  HiOutlineArrowLeft,
  HiOutlineArrowRight,
  HiOutlineRefresh,
  HiOutlineMenu,
  HiOutlineCheck,
  HiOutlineCheckCircle,
  HiOutlineChevronDown,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
  HiOutlineChevronUp,
  HiOutlineSelector,
  HiOutlineClock,
  HiOutlineHeart,
  HiOutlineHome,
  HiOutlineSearch,
  HiOutlineMinus,
  HiOutlinePlus,
  HiOutlinePhone,
  HiOutlineShoppingBag,
  HiOutlineUser,
  HiOutlineXCircle,
  HiOutlineX,
} from "react-icons/hi";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: HiOutlineArrowLeft,
  ArrowRight: HiOutlineArrowRight,
  ArrowPath: HiOutlineRefresh,
  Menu: HiOutlineMenu,
  Check: HiOutlineCheck,
  CheckCircle: HiOutlineCheckCircle,
  ChevronDown: HiOutlineChevronDown,
  ChevronLeft: HiOutlineChevronLeft,
  ChevronRight: HiOutlineChevronRight,
  ChevronUp: HiOutlineChevronUp,
  ChevronsUpDown: HiOutlineSelector,
  Clock: HiOutlineClock,
  Heart: HiOutlineHeart,
  Home: HiOutlineHome,
  Search: HiOutlineSearch,
  Minus: HiOutlineMinus,
  Plus: HiOutlinePlus,
  Cart: HiOutlineShoppingBag,
  User: HiOutlineUser,
  Phone: HiOutlinePhone,
  XCircle: HiOutlineXCircle,
  X: HiOutlineX,
};
