import {
  HiOutlineArrowLeft,
  HiOutlineArrowPath,
  HiOutlineArrowRight,
  HiBars3,
  HiOutlineCheck,
  HiOutlineCheckCircle,
  HiOutlineChevronDown,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
  HiOutlineChevronUp,
  HiOutlineChevronUpDown,
  HiOutlineClock,
  HiOutlineHeart,
  HiOutlineHome,
  HiOutlineMagnifyingGlass,
  HiOutlineMinus,
  HiOutlinePlus,
  HiOutlinePhone,
  HiOutlineShoppingBag,
  HiOutlineUser,
  HiOutlineXCircle,
  HiOutlineXMark,
} from "react-icons/hi2";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: HiOutlineArrowLeft,
  ArrowRight: HiOutlineArrowRight,
  ArrowPath: HiOutlineArrowPath,
  Menu: HiBars3,
  Check: HiOutlineCheck,
  CheckCircle: HiOutlineCheckCircle,
  ChevronDown: HiOutlineChevronDown,
  ChevronLeft: HiOutlineChevronLeft,
  ChevronRight: HiOutlineChevronRight,
  ChevronUp: HiOutlineChevronUp,
  ChevronsUpDown: HiOutlineChevronUpDown,
  Clock: HiOutlineClock,
  Heart: HiOutlineHeart,
  Home: HiOutlineHome,
  Search: HiOutlineMagnifyingGlass,
  Minus: HiOutlineMinus,
  Plus: HiOutlinePlus,
  Cart: HiOutlineShoppingBag,
  User: HiOutlineUser,
  Phone: HiOutlinePhone,
  XCircle: HiOutlineXCircle,
  X: HiOutlineXMark,
};
