import {
  IoArrowBack,
  IoArrowForward,
  IoRefresh,
  IoMenu,
  IoCheckmark,
  IoCheckmarkCircleOutline,
  IoChevronDown,
  IoChevronBack,
  IoChevronForward,
  IoChevronUp,
  IoSwapVertical,
  IoTimeOutline,
  IoHeartOutline,
  IoHomeOutline,
  IoSearchOutline,
  IoRemove,
  IoAdd,
  IoCallOutline,
  IoCartOutline,
  IoPersonOutline,
  IoCloseCircleOutline,
  IoClose,
} from "react-icons/io5";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: IoArrowBack,
  ArrowRight: IoArrowForward,
  ArrowPath: IoRefresh,
  Menu: IoMenu,
  Check: IoCheckmark,
  CheckCircle: IoCheckmarkCircleOutline,
  ChevronDown: IoChevronDown,
  ChevronLeft: IoChevronBack,
  ChevronRight: IoChevronForward,
  ChevronUp: IoChevronUp,
  ChevronsUpDown: IoSwapVertical,
  Clock: IoTimeOutline,
  Heart: IoHeartOutline,
  Home: IoHomeOutline,
  Search: IoSearchOutline,
  Minus: IoRemove,
  Plus: IoAdd,
  Cart: IoCartOutline,
  User: IoPersonOutline,
  Phone: IoCallOutline,
  XCircle: IoCloseCircleOutline,
  X: IoClose,
};
