import {
  LiaArrowLeftSolid,
  LiaArrowRightSolid,
  LiaRedoAltSolid,
  LiaBarsSolid,
  LiaCheckSolid,
  LiaCheckCircle,
  LiaChevronDownSolid,
  LiaChevronLeftSolid,
  LiaChevronRightSolid,
  LiaChevronUpSolid,
  LiaExchangeAltSolid,
  LiaClock,
  LiaHeart,
  LiaHomeSolid,
  LiaSearchSolid,
  LiaMinusSolid,
  LiaPlusSolid,
  LiaPhoneSolid,
  LiaShoppingBagSolid,
  LiaUser,
  LiaTimesCircle,
  LiaTimesSolid,
} from "react-icons/lia";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: LiaArrowLeftSolid,
  ArrowRight: LiaArrowRightSolid,
  ArrowPath: LiaRedoAltSolid,
  Menu: LiaBarsSolid,
  Check: LiaCheckSolid,
  CheckCircle: LiaCheckCircle,
  ChevronDown: LiaChevronDownSolid,
  ChevronLeft: LiaChevronLeftSolid,
  ChevronRight: LiaChevronRightSolid,
  ChevronUp: LiaChevronUpSolid,
  ChevronsUpDown: LiaExchangeAltSolid,
  Clock: LiaClock,
  Heart: LiaHeart,
  Home: LiaHomeSolid,
  Search: LiaSearchSolid,
  Minus: LiaMinusSolid,
  Plus: LiaPlusSolid,
  Cart: LiaShoppingBagSolid,
  User: LiaUser,
  Phone: LiaPhoneSolid,
  XCircle: LiaTimesCircle,
  X: LiaTimesSolid,
};
