import {
  MdArrowBack,
  MdArrowForward,
  MdRefresh,
  MdMenu,
  MdCheck,
  MdCheckCircleOutline,
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdKeyboardArrowUp,
  MdUnfoldMore,
  MdOutlineAccessTime,
  MdFavoriteBorder,
  MdOutlineHome,
  MdOutlineSearch,
  MdRemove,
  MdAdd,
  MdOutlinePhone,
  MdOutlineShoppingBag,
  MdOutlinePersonOutline,
  MdOutlineCancel,
  MdClose,
} from "react-icons/md";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: MdArrowBack,
  ArrowRight: MdArrowForward,
  ArrowPath: MdRefresh,
  Menu: MdMenu,
  Check: MdCheck,
  CheckCircle: MdCheckCircleOutline,
  ChevronDown: MdKeyboardArrowDown,
  ChevronLeft: MdKeyboardArrowLeft,
  ChevronRight: MdKeyboardArrowRight,
  ChevronUp: MdKeyboardArrowUp,
  ChevronsUpDown: MdUnfoldMore,
  Clock: MdOutlineAccessTime,
  Heart: MdFavoriteBorder,
  Home: MdOutlineHome,
  Search: MdOutlineSearch,
  Minus: MdRemove,
  Plus: MdAdd,
  Cart: MdOutlineShoppingBag,
  User: MdOutlinePersonOutline,
  Phone: MdOutlinePhone,
  XCircle: MdOutlineCancel,
  X: MdClose,
};
