import {
  PiArrowLeft,
  PiArrowRight,
  PiArrowsClockwise,
  PiList,
  PiCheck,
  PiCheckCircle,
  PiCaretDown,
  PiCaretLeft,
  PiCaretRight,
  PiCaretUp,
  PiCaretUpDown,
  PiClock,
  PiHeart,
  PiHouse,
  PiMagnifyingGlass,
  PiMinus,
  PiPlus,
  PiPhone,
  PiShoppingBag,
  PiUser,
  PiXCircle,
  PiX,
} from "react-icons/pi";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: PiArrowLeft,
  ArrowRight: PiArrowRight,
  ArrowPath: PiArrowsClockwise,
  Menu: PiList,
  Check: PiCheck,
  CheckCircle: PiCheckCircle,
  ChevronDown: PiCaretDown,
  ChevronLeft: PiCaretLeft,
  ChevronRight: PiCaretRight,
  ChevronUp: PiCaretUp,
  ChevronsUpDown: PiCaretUpDown,
  Clock: PiClock,
  Heart: PiHeart,
  Home: PiHouse,
  Search: PiMagnifyingGlass,
  Minus: PiMinus,
  Plus: PiPlus,
  Cart: PiShoppingBag,
  User: PiUser,
  Phone: PiPhone,
  XCircle: PiXCircle,
  X: PiX,
};
