import {
  RiArrowLeftLine,
  RiArrowRightLine,
  RiRefreshLine,
  RiMenuLine,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiArrowDownSLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiArrowUpSLine,
  RiExpandUpDownLine,
  RiTimeLine,
  RiHeartLine,
  RiHomeLine,
  RiSearchLine,
  RiSubtractLine,
  RiAddLine,
  RiPhoneLine,
  RiShoppingBagLine,
  RiUserLine,
  RiCloseCircleLine,
  RiCloseLine,
} from "react-icons/ri";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: RiArrowLeftLine,
  ArrowRight: RiArrowRightLine,
  ArrowPath: RiRefreshLine,
  Menu: RiMenuLine,
  Check: RiCheckLine,
  CheckCircle: RiCheckboxCircleLine,
  ChevronDown: RiArrowDownSLine,
  ChevronLeft: RiArrowLeftSLine,
  ChevronRight: RiArrowRightSLine,
  ChevronUp: RiArrowUpSLine,
  ChevronsUpDown: RiExpandUpDownLine,
  Clock: RiTimeLine,
  Heart: RiHeartLine,
  Home: RiHomeLine,
  Search: RiSearchLine,
  Minus: RiSubtractLine,
  Plus: RiAddLine,
  Cart: RiShoppingBagLine,
  User: RiUserLine,
  Phone: RiPhoneLine,
  XCircle: RiCloseCircleLine,
  X: RiCloseLine,
};
