import {
  RxArrowLeft,
  RxArrowRight,
  RxReload,
  RxHamburgerMenu,
  RxCheck,
  RxCheckCircled,
  RxChevronDown,
  RxChevronLeft,
  RxChevronRight,
  RxChevronUp,
  RxCaretSort,
  RxClock,
  RxHeart,
  RxHome,
  RxMagnifyingGlass,
  RxMinus,
  RxPlus,
  RxMobile,
  RxCube,
  RxPerson,
  RxCrossCircled,
  RxCross2,
} from "react-icons/rx";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: RxArrowLeft,
  ArrowRight: RxArrowRight,
  ArrowPath: RxReload,
  Menu: RxHamburgerMenu,
  Check: RxCheck,
  CheckCircle: RxCheckCircled,
  ChevronDown: RxChevronDown,
  ChevronLeft: RxChevronLeft,
  ChevronRight: RxChevronRight,
  ChevronUp: RxChevronUp,
  ChevronsUpDown: RxCaretSort,
  Clock: RxClock,
  Heart: RxHeart,
  Home: RxHome,
  Search: RxMagnifyingGlass,
  Minus: RxMinus,
  Plus: RxPlus,
  Cart: RxCube,
  User: RxPerson,
  Phone: RxMobile,
  XCircle: RxCrossCircled,
  X: RxCross2,
};
