import {
  TbArrowLeft,
  TbArrowRight,
  TbRefresh,
  TbMenu2,
  TbCheck,
  TbCircleCheck,
  TbChevronDown,
  TbChevronLeft,
  TbChevronRight,
  TbChevronUp,
  TbSelector,
  TbClock,
  TbHeart,
  TbHome,
  TbSearch,
  TbMinus,
  TbPlus,
  TbPhone,
  TbShoppingBag,
  TbUser,
  TbCircleX,
  TbX,
} from "react-icons/tb";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: TbArrowLeft,
  ArrowRight: TbArrowRight,
  ArrowPath: TbRefresh,
  Menu: TbMenu2,
  Check: TbCheck,
  CheckCircle: TbCircleCheck,
  ChevronDown: TbChevronDown,
  ChevronLeft: TbChevronLeft,
  ChevronRight: TbChevronRight,
  ChevronUp: TbChevronUp,
  ChevronsUpDown: TbSelector,
  Clock: TbClock,
  Heart: TbHeart,
  Home: TbHome,
  Search: TbSearch,
  Minus: TbMinus,
  Plus: TbPlus,
  Cart: TbShoppingBag,
  User: TbUser,
  Phone: TbPhone,
  XCircle: TbCircleX,
  X: TbX,
};
