import {
  TfiArrowLeft,
  TfiArrowRight,
  TfiReload,
  TfiMenu,
  TfiCheck,
  TfiCheckBox,
  TfiAngleDown,
  TfiAngleLeft,
  TfiAngleRight,
  TfiAngleUp,
  TfiArrowsVertical,
  TfiTimer,
  TfiHeart,
  TfiHome,
  TfiSearch,
  TfiMinus,
  TfiPlus,
  TfiMobile,
  TfiShoppingCart,
  TfiUser,
  TfiClose,
  TfiClose as TfiX,
} from "react-icons/tfi";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: TfiArrowLeft,
  ArrowRight: TfiArrowRight,
  ArrowPath: TfiReload,
  Menu: TfiMenu,
  Check: TfiCheck,
  CheckCircle: TfiCheckBox,
  ChevronDown: TfiAngleDown,
  ChevronLeft: TfiAngleLeft,
  ChevronRight: TfiAngleRight,
  ChevronUp: TfiAngleUp,
  ChevronsUpDown: TfiArrowsVertical,
  Clock: TfiTimer,
  Heart: TfiHeart,
  Home: TfiHome,
  Search: TfiSearch,
  Minus: TfiMinus,
  Plus: TfiPlus,
  Cart: TfiShoppingCart,
  User: TfiUser,
  Phone: TfiMobile,
  XCircle: TfiClose,
  X: TfiX,
};
