import {
  TiArrowLeft,
  TiArrowRight,
  TiArrowSync,
  TiThMenu,
  TiTick,
  TiTickOutline,
  TiArrowSortedDown,
  TiChevronLeft,
  TiChevronRight,
  TiArrowSortedUp,
  TiArrowUpThick,
  TiTime,
  TiHeartOutline,
  TiHome,
  TiZoomOutline,
  TiMinus,
  TiPlus,
  TiPhoneOutline,
  TiShoppingCart,
  TiUserOutline,
  TiDeleteOutline,
  TiTimes,
} from "react-icons/ti";
import type { BrandUiIcons } from "./types";

export const icons: BrandUiIcons = {
  ArrowLeft: TiArrowLeft,
  ArrowRight: TiArrowRight,
  ArrowPath: TiArrowSync,
  Menu: TiThMenu,
  Check: TiTick,
  CheckCircle: TiTickOutline,
  ChevronDown: TiArrowSortedDown,
  ChevronLeft: TiChevronLeft,
  ChevronRight: TiChevronRight,
  ChevronUp: TiArrowSortedUp,
  ChevronsUpDown: TiArrowUpThick,
  Clock: TiTime,
  Heart: TiHeartOutline,
  Home: TiHome,
  Search: TiZoomOutline,
  Minus: TiMinus,
  Plus: TiPlus,
  Cart: TiShoppingCart,
  User: TiUserOutline,
  Phone: TiPhoneOutline,
  XCircle: TiDeleteOutline,
  X: TiTimes,
};
